### ISSUE TITLE
Subtotal table by one or more columns

### ISSUE THREAD

**Issue by Mary2424** [Mary2424/FiPCE#1]
User identifies one or more columns (could be columns currently sorted by)
Subtotal lines would be added for each unique combination of the identified fields for summable fields only.

**Comment by ngbb** [comment]
I'm thinking of possibly adding a radio button to the side panel that would select either "edit" mode or "explore" mode. In edit mode, the user would see the entire dataset and be able to edit cells (more or less what is currently implemented).

In explore mode, the dataset would "lock" and the user could select columns as input to a dplyr call of group_by() and summarize_each(), and the result would be displayed.

Thoughts? The downside is that the user would have to switch between datasets to edit and then see the changes, but the plus side is that it's much easier to implement.

**Comment by Mary2424** [comment]
I'm closing this issue and combine it with the "Subtotal table by one or more columns" issue renamed to "Collapse table by totaling over groups defined by one or more columns". https://github.com/Mary2424/FiPCE/issues/2
